### PR TITLE
Add node and refactor

### PR DESCRIPTION
**Pull request by DirtyRacer1337**

### CODE REVIEW

**Comment by 4c0d3r** [comment]
Would you mind adding a section to pyproject.toml to call the yarn build?   This would ensure bad releases aren't cut.   Right now Dockerfile builds would fail (wouldn't get the js) - as well as the pip build in the job that cuts the release in github actions.

I think it's possible due to the last answer here:    https://stackoverflow.com/questions/59286983/how-to-run-a-script-using-pyproject-toml-settings-and-poetry

**Comment by 4c0d3r** [comment]
Here's the source documentation:   https://github.com/nat-n/poethepoet#hooking-into-poetry-commands

**Comment by 4c0d3r** [comment]
Dockerfile as well, it'll build, but wont have the minified js.

**Comment by 4c0d3r** [comment]
I'm always torn on minifying outside of the proper build process, hence the ask for the poetry build hooks, would solve a lot of the finagling.   compressing in a filter, while limited to individual files, tends to always just work and prevents build complexity.   plus if someone wanted to audit what was being built/done, tends to be a bit easier for the paranoid, or busy dev working on a bug fix.    but not going to push on this either way, just sharing concerns.

**Comment by DirtyRacer1337** [comment]
Can't make hook to regular `poetry build` (maybe I'm too dumb for it)

**Comment by 4c0d3r** [comment]
I can handle the docker stuff, but think the poethepoet extension to poetry could make all of this easier

**Comment by DirtyRacer1337** [comment]
ok, I'm giving up, docker won this battle

**Comment by DirtyRacer1337** [comment]
at least, now I understand why it's doesn't work

**Comment by 4c0d3r** [comment]
I want to understand the desire for full magnification of css and js?

The way I see it we have two times we really care:
1) On the wire
2) When stored (on the server/client).

There are tradeoffs with compressing all the js together though.   If the user already has bootstrap (pre-minified) and jquery in there browser cache there's no cost them to load these files.    It's only the app specific js/css that have cost.

Here's an alternative:

If we want to save wire time:    https://github.com/colour-science/flask-compress could handle most of the concern for us by compressing on the wire all html/css/js for us.    Developers could also still easily audit the code, and the build would stay simpler.    The cost would be hire local cpu.   This could be (and hopefully) already is minimized by a local cache of static files already compressed.    Hopefully browser will cache the static files and all will be well - which would still just be one for css and one for javascript.

What do you think?

Is the simplicity of using a filter in flask and the slightly hire cpu a better tradeoff than the complexity of the current solution.   Does it meet all your desired goals as well?

**Comment by 4c0d3r** [comment]
To be clear I think flask compress is enough without minifying all the js/css in the build.   I'm not trying minimize the work you've done, but afraid the trade-off of the build complexity of using node isn't really worth the value add when compared to flask-compress on it's own.

**Pull request merged**
