### PR TITLE
add videohash support

### PR DESCRIPTION
**Pull request by 4c0d3r**

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
You still need `ImageHash` module to calculate distances, check tests

**Comment by DirtyRacer1337** [comment]
alsi, it's builded already, https://github.com/peolic/videohashes/releases

**Comment by 4c0d3r** [comment]
There's a comparison executable (haven't tried it yet), but I'm hoping to use that as well to determine distance/matches - copied it over.

**Comment by DirtyRacer1337** [comment]
it's faster that run exe

**Comment by 4c0d3r** [comment]
@DirtyRacer1337 even though it's built already, it wasn't built with GitHub actions, so the provenance of the executables can't be verified by the curious user.   I'm moving the build here so that the source of the artifacts can be verified.

**Comment by 4c0d3r** [comment]
Still a WIP but much improved installation and workflow, so merging.   Also _think_ the race condition in watchdog tests might be solved, else good logging will help identify the problem.

**Pull request merged**
